// File generated by the BNF Converter (bnfc 2.9.6).

package ru.itmo.stella.lang.Absyn;

public class ATyping extends Typing {
  public final Expr expr_;
  public final Type type_;
  public int line_num, col_num, offset;
  public ATyping(Expr p1, Type p2) { expr_ = p1; type_ = p2; }

  public <R,A> R accept(ru.itmo.stella.lang.Absyn.Typing.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof ru.itmo.stella.lang.Absyn.ATyping) {
      ru.itmo.stella.lang.Absyn.ATyping x = (ru.itmo.stella.lang.Absyn.ATyping)o;
      return this.expr_.equals(x.expr_) && this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expr_.hashCode())+this.type_.hashCode();
  }


}
