// File generated by the BNF Converter (bnfc 2.9.6).

package ru.itmo.stella.lang.Absyn;

public class AVariantFieldType extends VariantFieldType {
  public final String stellaident_;
  public final OptionalTyping optionaltyping_;
  public int line_num, col_num, offset;
  public AVariantFieldType(String p1, OptionalTyping p2) { stellaident_ = p1; optionaltyping_ = p2; }

  public <R,A> R accept(ru.itmo.stella.lang.Absyn.VariantFieldType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof ru.itmo.stella.lang.Absyn.AVariantFieldType) {
      ru.itmo.stella.lang.Absyn.AVariantFieldType x = (ru.itmo.stella.lang.Absyn.AVariantFieldType)o;
      return this.stellaident_.equals(x.stellaident_) && this.optionaltyping_.equals(x.optionaltyping_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.stellaident_.hashCode())+this.optionaltyping_.hashCode();
  }


}
