// File generated by the BNF Converter (bnfc 2.9.6).

package ru.itmo.stella.lang.Absyn;

public abstract class Decl implements java.io.Serializable {
  public abstract <R,A> R accept(Decl.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(ru.itmo.stella.lang.Absyn.DeclFun p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.DeclFunGeneric p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.DeclTypeAlias p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.DeclExceptionType p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.DeclExceptionVariant p, A arg);

  }

}
