// File generated by the BNF Converter (bnfc 2.9.6).

package ru.itmo.stella.lang.Absyn;

public abstract class Pattern implements java.io.Serializable {
  public abstract <R,A> R accept(Pattern.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(ru.itmo.stella.lang.Absyn.PatternCastAs p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.PatternAsc p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.PatternVariant p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.PatternInl p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.PatternInr p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.PatternTuple p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.PatternRecord p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.PatternList p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.PatternCons p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.PatternFalse p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.PatternTrue p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.PatternUnit p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.PatternInt p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.PatternSucc p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.PatternVar p, A arg);

  }

}
