// File generated by the BNF Converter (bnfc 2.9.6).

package ru.itmo.stella.lang.Absyn;

public abstract class PatternData implements java.io.Serializable {
  public abstract <R,A> R accept(PatternData.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(ru.itmo.stella.lang.Absyn.NoPatternData p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.SomePatternData p, A arg);

  }

}
