// File generated by the BNF Converter (bnfc 2.9.6).

package ru.itmo.stella.lang.Absyn;

public class PatternRecord extends Pattern {
  public final ListLabelledPattern listlabelledpattern_;
  public int line_num, col_num, offset;
  public PatternRecord(ListLabelledPattern p1) { listlabelledpattern_ = p1; }

  public <R,A> R accept(ru.itmo.stella.lang.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof ru.itmo.stella.lang.Absyn.PatternRecord) {
      ru.itmo.stella.lang.Absyn.PatternRecord x = (ru.itmo.stella.lang.Absyn.PatternRecord)o;
      return this.listlabelledpattern_.equals(x.listlabelledpattern_);
    }
    return false;
  }

  public int hashCode() {
    return this.listlabelledpattern_.hashCode();
  }


}
