// File generated by the BNF Converter (bnfc 2.9.6).

package ru.itmo.stella.lang.Absyn;

public class PatternAsc extends Pattern {
  public final Pattern pattern_;
  public final Type type_;
  public int line_num, col_num, offset;
  public PatternAsc(Pattern p1, Type p2) { pattern_ = p1; type_ = p2; }

  public <R,A> R accept(ru.itmo.stella.lang.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof ru.itmo.stella.lang.Absyn.PatternAsc) {
      ru.itmo.stella.lang.Absyn.PatternAsc x = (ru.itmo.stella.lang.Absyn.PatternAsc)o;
      return this.pattern_.equals(x.pattern_) && this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.pattern_.hashCode())+this.type_.hashCode();
  }


}
