// File generated by the BNF Converter (bnfc 2.9.6).

package ru.itmo.stella.lang.Absyn;

public class Tuple extends Expr {
  public final ListExpr listexpr_;
  public int line_num, col_num, offset;
  public Tuple(ListExpr p1) { listexpr_ = p1; }

  public <R,A> R accept(ru.itmo.stella.lang.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof ru.itmo.stella.lang.Absyn.Tuple) {
      ru.itmo.stella.lang.Absyn.Tuple x = (ru.itmo.stella.lang.Absyn.Tuple)o;
      return this.listexpr_.equals(x.listexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.listexpr_.hashCode();
  }


}
