// File generated by the BNF Converter (bnfc 2.9.6).

package ru.itmo.stella.lang;

public class AbsynDef {

  public static <B,A extends java.util.LinkedList<? super B>> A cons(B x, A xs) {
    xs.addFirst(x);
    return xs;
  }

  public static ru.itmo.stella.lang.Absyn.Pattern patternCons(ru.itmo.stella.lang.Absyn.Pattern h, ru.itmo.stella.lang.Absyn.Pattern t) {
    return new ru.itmo.stella.lang.Absyn.PatternCons(h, t);
  }

}
