// File generated by the BNF Converter (bnfc 2.9.6).

package ru.itmo.stella.lang.Absyn;

public class ConstMemory extends Expr {
  public final String memoryaddress_;
  public int line_num, col_num, offset;
  public ConstMemory(String p1) { memoryaddress_ = p1; }

  public <R,A> R accept(ru.itmo.stella.lang.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof ru.itmo.stella.lang.Absyn.ConstMemory) {
      ru.itmo.stella.lang.Absyn.ConstMemory x = (ru.itmo.stella.lang.Absyn.ConstMemory)o;
      return this.memoryaddress_.equals(x.memoryaddress_);
    }
    return false;
  }

  public int hashCode() {
    return this.memoryaddress_.hashCode();
  }


}
