// File generated by the BNF Converter (bnfc 2.9.6).

package ru.itmo.stella.lang.Absyn;

public abstract class ExprData implements java.io.Serializable {
  public abstract <R,A> R accept(ExprData.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(ru.itmo.stella.lang.Absyn.NoExprData p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.SomeExprData p, A arg);

  }

}
