// File generated by the BNF Converter (bnfc 2.9.6).

package ru.itmo.stella.lang.Absyn;

public abstract class LanguageDecl implements java.io.Serializable {
  public abstract <R,A> R accept(LanguageDecl.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(ru.itmo.stella.lang.Absyn.LanguageCore p, A arg);

  }

}
