// File generated by the BNF Converter (bnfc 2.9.6).

package ru.itmo.stella.lang.Absyn;

public class PatternVar extends Pattern {
  public final String stellaident_;
  public int line_num, col_num, offset;
  public PatternVar(String p1) { stellaident_ = p1; }

  public <R,A> R accept(ru.itmo.stella.lang.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof ru.itmo.stella.lang.Absyn.PatternVar) {
      ru.itmo.stella.lang.Absyn.PatternVar x = (ru.itmo.stella.lang.Absyn.PatternVar)o;
      return this.stellaident_.equals(x.stellaident_);
    }
    return false;
  }

  public int hashCode() {
    return this.stellaident_.hashCode();
  }


}
