// File generated by the BNF Converter (bnfc 2.9.6).

package ru.itmo.stella.lang.Absyn;

public class TypeTuple extends Type {
  public final ListType listtype_;
  public int line_num, col_num, offset;
  public TypeTuple(ListType p1) { listtype_ = p1; }

  public <R,A> R accept(ru.itmo.stella.lang.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof ru.itmo.stella.lang.Absyn.TypeTuple) {
      ru.itmo.stella.lang.Absyn.TypeTuple x = (ru.itmo.stella.lang.Absyn.TypeTuple)o;
      return this.listtype_.equals(x.listtype_);
    }
    return false;
  }

  public int hashCode() {
    return this.listtype_.hashCode();
  }


}
