// File generated by the BNF Converter (bnfc 2.9.6).

package ru.itmo.stella.lang.Absyn;

public abstract class Type implements java.io.Serializable {
  public abstract <R,A> R accept(Type.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(ru.itmo.stella.lang.Absyn.TypeAuto p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.TypeFun p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.TypeForAll p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.TypeRec p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.TypeSum p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.TypeTuple p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.TypeRecord p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.TypeVariant p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.TypeList p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.TypeBool p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.TypeNat p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.TypeUnit p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.TypeTop p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.TypeBottom p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.TypeRef p, A arg);
    public R visit(ru.itmo.stella.lang.Absyn.TypeVar p, A arg);

  }

}
