// File generated by the BNF Converter (bnfc 2.9.6).

package ru.itmo.stella.lang.Absyn;

public class Unfold extends Expr {
  public final Type type_;
  public final Expr expr_;
  public int line_num, col_num, offset;
  public Unfold(Type p1, Expr p2) { type_ = p1; expr_ = p2; }

  public <R,A> R accept(ru.itmo.stella.lang.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof ru.itmo.stella.lang.Absyn.Unfold) {
      ru.itmo.stella.lang.Absyn.Unfold x = (ru.itmo.stella.lang.Absyn.Unfold)o;
      return this.type_.equals(x.type_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_.hashCode())+this.expr_.hashCode();
  }


}
