// File generated by the BNF Converter (bnfc 2.9.6).

package ru.itmo.stella.lang.stella;
/** Composition Visitor
*/

public class ComposVisitor<A> implements
  ru.itmo.stella.lang.Absyn.Program.Visitor<ru.itmo.stella.lang.Absyn.Program,A>,
  ru.itmo.stella.lang.Absyn.LanguageDecl.Visitor<ru.itmo.stella.lang.Absyn.LanguageDecl,A>,
  ru.itmo.stella.lang.Absyn.Extension.Visitor<ru.itmo.stella.lang.Absyn.Extension,A>,
  ru.itmo.stella.lang.Absyn.Decl.Visitor<ru.itmo.stella.lang.Absyn.Decl,A>,
  ru.itmo.stella.lang.Absyn.LocalDecl.Visitor<ru.itmo.stella.lang.Absyn.LocalDecl,A>,
  ru.itmo.stella.lang.Absyn.Annotation.Visitor<ru.itmo.stella.lang.Absyn.Annotation,A>,
  ru.itmo.stella.lang.Absyn.ParamDecl.Visitor<ru.itmo.stella.lang.Absyn.ParamDecl,A>,
  ru.itmo.stella.lang.Absyn.ReturnType.Visitor<ru.itmo.stella.lang.Absyn.ReturnType,A>,
  ru.itmo.stella.lang.Absyn.ThrowType.Visitor<ru.itmo.stella.lang.Absyn.ThrowType,A>,
  ru.itmo.stella.lang.Absyn.Type.Visitor<ru.itmo.stella.lang.Absyn.Type,A>,
  ru.itmo.stella.lang.Absyn.MatchCase.Visitor<ru.itmo.stella.lang.Absyn.MatchCase,A>,
  ru.itmo.stella.lang.Absyn.OptionalTyping.Visitor<ru.itmo.stella.lang.Absyn.OptionalTyping,A>,
  ru.itmo.stella.lang.Absyn.PatternData.Visitor<ru.itmo.stella.lang.Absyn.PatternData,A>,
  ru.itmo.stella.lang.Absyn.ExprData.Visitor<ru.itmo.stella.lang.Absyn.ExprData,A>,
  ru.itmo.stella.lang.Absyn.Pattern.Visitor<ru.itmo.stella.lang.Absyn.Pattern,A>,
  ru.itmo.stella.lang.Absyn.LabelledPattern.Visitor<ru.itmo.stella.lang.Absyn.LabelledPattern,A>,
  ru.itmo.stella.lang.Absyn.Binding.Visitor<ru.itmo.stella.lang.Absyn.Binding,A>,
  ru.itmo.stella.lang.Absyn.Expr.Visitor<ru.itmo.stella.lang.Absyn.Expr,A>,
  ru.itmo.stella.lang.Absyn.PatternBinding.Visitor<ru.itmo.stella.lang.Absyn.PatternBinding,A>,
  ru.itmo.stella.lang.Absyn.VariantFieldType.Visitor<ru.itmo.stella.lang.Absyn.VariantFieldType,A>,
  ru.itmo.stella.lang.Absyn.RecordFieldType.Visitor<ru.itmo.stella.lang.Absyn.RecordFieldType,A>,
  ru.itmo.stella.lang.Absyn.Typing.Visitor<ru.itmo.stella.lang.Absyn.Typing,A>
{
    /* Program */
    public ru.itmo.stella.lang.Absyn.Program visit(ru.itmo.stella.lang.Absyn.AProgram p, A arg)
    {
      ru.itmo.stella.lang.Absyn.LanguageDecl languagedecl_ = p.languagedecl_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.ListExtension listextension_ = new ru.itmo.stella.lang.Absyn.ListExtension();
      for (ru.itmo.stella.lang.Absyn.Extension x : p.listextension_)
      {
        listextension_.add(x.accept(this,arg));
      }
      ru.itmo.stella.lang.Absyn.ListDecl listdecl_ = new ru.itmo.stella.lang.Absyn.ListDecl();
      for (ru.itmo.stella.lang.Absyn.Decl x : p.listdecl_)
      {
        listdecl_.add(x.accept(this,arg));
      }
      return new ru.itmo.stella.lang.Absyn.AProgram(languagedecl_, listextension_, listdecl_);
    }

    /* LanguageDecl */
    public ru.itmo.stella.lang.Absyn.LanguageDecl visit(ru.itmo.stella.lang.Absyn.LanguageCore p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.LanguageCore();
    }

    /* Extension */
    public ru.itmo.stella.lang.Absyn.Extension visit(ru.itmo.stella.lang.Absyn.AnExtension p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListExtensionName listextensionname_ = p.listextensionname_;
      return new ru.itmo.stella.lang.Absyn.AnExtension(listextensionname_);
    }

    /* Decl */
    public ru.itmo.stella.lang.Absyn.Decl visit(ru.itmo.stella.lang.Absyn.DeclFun p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListAnnotation listannotation_ = new ru.itmo.stella.lang.Absyn.ListAnnotation();
      for (ru.itmo.stella.lang.Absyn.Annotation x : p.listannotation_)
      {
        listannotation_.add(x.accept(this,arg));
      }
      String stellaident_ = p.stellaident_;
      ru.itmo.stella.lang.Absyn.ListParamDecl listparamdecl_ = new ru.itmo.stella.lang.Absyn.ListParamDecl();
      for (ru.itmo.stella.lang.Absyn.ParamDecl x : p.listparamdecl_)
      {
        listparamdecl_.add(x.accept(this,arg));
      }
      ru.itmo.stella.lang.Absyn.ReturnType returntype_ = p.returntype_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.ThrowType throwtype_ = p.throwtype_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.ListDecl listdecl_ = new ru.itmo.stella.lang.Absyn.ListDecl();
      for (ru.itmo.stella.lang.Absyn.Decl x : p.listdecl_)
      {
        listdecl_.add(x.accept(this,arg));
      }
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.DeclFun(listannotation_, stellaident_, listparamdecl_, returntype_, throwtype_, listdecl_, expr_);
    }
    public ru.itmo.stella.lang.Absyn.Decl visit(ru.itmo.stella.lang.Absyn.DeclFunGeneric p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListAnnotation listannotation_ = new ru.itmo.stella.lang.Absyn.ListAnnotation();
      for (ru.itmo.stella.lang.Absyn.Annotation x : p.listannotation_)
      {
        listannotation_.add(x.accept(this,arg));
      }
      String stellaident_ = p.stellaident_;
      ru.itmo.stella.lang.Absyn.ListStellaIdent liststellaident_ = p.liststellaident_;
      ru.itmo.stella.lang.Absyn.ListParamDecl listparamdecl_ = new ru.itmo.stella.lang.Absyn.ListParamDecl();
      for (ru.itmo.stella.lang.Absyn.ParamDecl x : p.listparamdecl_)
      {
        listparamdecl_.add(x.accept(this,arg));
      }
      ru.itmo.stella.lang.Absyn.ReturnType returntype_ = p.returntype_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.ThrowType throwtype_ = p.throwtype_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.ListDecl listdecl_ = new ru.itmo.stella.lang.Absyn.ListDecl();
      for (ru.itmo.stella.lang.Absyn.Decl x : p.listdecl_)
      {
        listdecl_.add(x.accept(this,arg));
      }
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.DeclFunGeneric(listannotation_, stellaident_, liststellaident_, listparamdecl_, returntype_, throwtype_, listdecl_, expr_);
    }
    public ru.itmo.stella.lang.Absyn.Decl visit(ru.itmo.stella.lang.Absyn.DeclTypeAlias p, A arg)
    {
      String stellaident_ = p.stellaident_;
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.DeclTypeAlias(stellaident_, type_);
    }
    public ru.itmo.stella.lang.Absyn.Decl visit(ru.itmo.stella.lang.Absyn.DeclExceptionType p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.DeclExceptionType(type_);
    }
    public ru.itmo.stella.lang.Absyn.Decl visit(ru.itmo.stella.lang.Absyn.DeclExceptionVariant p, A arg)
    {
      String stellaident_ = p.stellaident_;
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.DeclExceptionVariant(stellaident_, type_);
    }

    /* LocalDecl */
    public ru.itmo.stella.lang.Absyn.LocalDecl visit(ru.itmo.stella.lang.Absyn.ALocalDecl p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Decl decl_ = p.decl_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.ALocalDecl(decl_);
    }

    /* Annotation */
    public ru.itmo.stella.lang.Absyn.Annotation visit(ru.itmo.stella.lang.Absyn.InlineAnnotation p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.InlineAnnotation();
    }

    /* ParamDecl */
    public ru.itmo.stella.lang.Absyn.ParamDecl visit(ru.itmo.stella.lang.Absyn.AParamDecl p, A arg)
    {
      String stellaident_ = p.stellaident_;
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.AParamDecl(stellaident_, type_);
    }

    /* ReturnType */
    public ru.itmo.stella.lang.Absyn.ReturnType visit(ru.itmo.stella.lang.Absyn.NoReturnType p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.NoReturnType();
    }
    public ru.itmo.stella.lang.Absyn.ReturnType visit(ru.itmo.stella.lang.Absyn.SomeReturnType p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.SomeReturnType(type_);
    }

    /* ThrowType */
    public ru.itmo.stella.lang.Absyn.ThrowType visit(ru.itmo.stella.lang.Absyn.NoThrowType p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.NoThrowType();
    }
    public ru.itmo.stella.lang.Absyn.ThrowType visit(ru.itmo.stella.lang.Absyn.SomeThrowType p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListType listtype_ = new ru.itmo.stella.lang.Absyn.ListType();
      for (ru.itmo.stella.lang.Absyn.Type x : p.listtype_)
      {
        listtype_.add(x.accept(this,arg));
      }
      return new ru.itmo.stella.lang.Absyn.SomeThrowType(listtype_);
    }

    /* Type */
    public ru.itmo.stella.lang.Absyn.Type visit(ru.itmo.stella.lang.Absyn.TypeAuto p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.TypeAuto();
    }
    public ru.itmo.stella.lang.Absyn.Type visit(ru.itmo.stella.lang.Absyn.TypeFun p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListType listtype_ = new ru.itmo.stella.lang.Absyn.ListType();
      for (ru.itmo.stella.lang.Absyn.Type x : p.listtype_)
      {
        listtype_.add(x.accept(this,arg));
      }
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.TypeFun(listtype_, type_);
    }
    public ru.itmo.stella.lang.Absyn.Type visit(ru.itmo.stella.lang.Absyn.TypeForAll p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListStellaIdent liststellaident_ = p.liststellaident_;
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.TypeForAll(liststellaident_, type_);
    }
    public ru.itmo.stella.lang.Absyn.Type visit(ru.itmo.stella.lang.Absyn.TypeRec p, A arg)
    {
      String stellaident_ = p.stellaident_;
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.TypeRec(stellaident_, type_);
    }
    public ru.itmo.stella.lang.Absyn.Type visit(ru.itmo.stella.lang.Absyn.TypeSum p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Type type_1 = p.type_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Type type_2 = p.type_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.TypeSum(type_1, type_2);
    }
    public ru.itmo.stella.lang.Absyn.Type visit(ru.itmo.stella.lang.Absyn.TypeTuple p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListType listtype_ = new ru.itmo.stella.lang.Absyn.ListType();
      for (ru.itmo.stella.lang.Absyn.Type x : p.listtype_)
      {
        listtype_.add(x.accept(this,arg));
      }
      return new ru.itmo.stella.lang.Absyn.TypeTuple(listtype_);
    }
    public ru.itmo.stella.lang.Absyn.Type visit(ru.itmo.stella.lang.Absyn.TypeRecord p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListRecordFieldType listrecordfieldtype_ = new ru.itmo.stella.lang.Absyn.ListRecordFieldType();
      for (ru.itmo.stella.lang.Absyn.RecordFieldType x : p.listrecordfieldtype_)
      {
        listrecordfieldtype_.add(x.accept(this,arg));
      }
      return new ru.itmo.stella.lang.Absyn.TypeRecord(listrecordfieldtype_);
    }
    public ru.itmo.stella.lang.Absyn.Type visit(ru.itmo.stella.lang.Absyn.TypeVariant p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListVariantFieldType listvariantfieldtype_ = new ru.itmo.stella.lang.Absyn.ListVariantFieldType();
      for (ru.itmo.stella.lang.Absyn.VariantFieldType x : p.listvariantfieldtype_)
      {
        listvariantfieldtype_.add(x.accept(this,arg));
      }
      return new ru.itmo.stella.lang.Absyn.TypeVariant(listvariantfieldtype_);
    }
    public ru.itmo.stella.lang.Absyn.Type visit(ru.itmo.stella.lang.Absyn.TypeList p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.TypeList(type_);
    }
    public ru.itmo.stella.lang.Absyn.Type visit(ru.itmo.stella.lang.Absyn.TypeBool p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.TypeBool();
    }
    public ru.itmo.stella.lang.Absyn.Type visit(ru.itmo.stella.lang.Absyn.TypeNat p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.TypeNat();
    }
    public ru.itmo.stella.lang.Absyn.Type visit(ru.itmo.stella.lang.Absyn.TypeUnit p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.TypeUnit();
    }
    public ru.itmo.stella.lang.Absyn.Type visit(ru.itmo.stella.lang.Absyn.TypeTop p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.TypeTop();
    }
    public ru.itmo.stella.lang.Absyn.Type visit(ru.itmo.stella.lang.Absyn.TypeBottom p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.TypeBottom();
    }
    public ru.itmo.stella.lang.Absyn.Type visit(ru.itmo.stella.lang.Absyn.TypeRef p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.TypeRef(type_);
    }
    public ru.itmo.stella.lang.Absyn.Type visit(ru.itmo.stella.lang.Absyn.TypeVar p, A arg)
    {
      String stellaident_ = p.stellaident_;
      return new ru.itmo.stella.lang.Absyn.TypeVar(stellaident_);
    }

    /* MatchCase */
    public ru.itmo.stella.lang.Absyn.MatchCase visit(ru.itmo.stella.lang.Absyn.AMatchCase p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Pattern pattern_ = p.pattern_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.AMatchCase(pattern_, expr_);
    }

    /* OptionalTyping */
    public ru.itmo.stella.lang.Absyn.OptionalTyping visit(ru.itmo.stella.lang.Absyn.NoTyping p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.NoTyping();
    }
    public ru.itmo.stella.lang.Absyn.OptionalTyping visit(ru.itmo.stella.lang.Absyn.SomeTyping p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.SomeTyping(type_);
    }

    /* PatternData */
    public ru.itmo.stella.lang.Absyn.PatternData visit(ru.itmo.stella.lang.Absyn.NoPatternData p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.NoPatternData();
    }
    public ru.itmo.stella.lang.Absyn.PatternData visit(ru.itmo.stella.lang.Absyn.SomePatternData p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Pattern pattern_ = p.pattern_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.SomePatternData(pattern_);
    }

    /* ExprData */
    public ru.itmo.stella.lang.Absyn.ExprData visit(ru.itmo.stella.lang.Absyn.NoExprData p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.NoExprData();
    }
    public ru.itmo.stella.lang.Absyn.ExprData visit(ru.itmo.stella.lang.Absyn.SomeExprData p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.SomeExprData(expr_);
    }

    /* Pattern */
    public ru.itmo.stella.lang.Absyn.Pattern visit(ru.itmo.stella.lang.Absyn.PatternCastAs p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Pattern pattern_ = p.pattern_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.PatternCastAs(pattern_, type_);
    }
    public ru.itmo.stella.lang.Absyn.Pattern visit(ru.itmo.stella.lang.Absyn.PatternAsc p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Pattern pattern_ = p.pattern_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.PatternAsc(pattern_, type_);
    }
    public ru.itmo.stella.lang.Absyn.Pattern visit(ru.itmo.stella.lang.Absyn.PatternVariant p, A arg)
    {
      String stellaident_ = p.stellaident_;
      ru.itmo.stella.lang.Absyn.PatternData patterndata_ = p.patterndata_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.PatternVariant(stellaident_, patterndata_);
    }
    public ru.itmo.stella.lang.Absyn.Pattern visit(ru.itmo.stella.lang.Absyn.PatternInl p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Pattern pattern_ = p.pattern_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.PatternInl(pattern_);
    }
    public ru.itmo.stella.lang.Absyn.Pattern visit(ru.itmo.stella.lang.Absyn.PatternInr p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Pattern pattern_ = p.pattern_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.PatternInr(pattern_);
    }
    public ru.itmo.stella.lang.Absyn.Pattern visit(ru.itmo.stella.lang.Absyn.PatternTuple p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListPattern listpattern_ = new ru.itmo.stella.lang.Absyn.ListPattern();
      for (ru.itmo.stella.lang.Absyn.Pattern x : p.listpattern_)
      {
        listpattern_.add(x.accept(this,arg));
      }
      return new ru.itmo.stella.lang.Absyn.PatternTuple(listpattern_);
    }
    public ru.itmo.stella.lang.Absyn.Pattern visit(ru.itmo.stella.lang.Absyn.PatternRecord p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListLabelledPattern listlabelledpattern_ = new ru.itmo.stella.lang.Absyn.ListLabelledPattern();
      for (ru.itmo.stella.lang.Absyn.LabelledPattern x : p.listlabelledpattern_)
      {
        listlabelledpattern_.add(x.accept(this,arg));
      }
      return new ru.itmo.stella.lang.Absyn.PatternRecord(listlabelledpattern_);
    }
    public ru.itmo.stella.lang.Absyn.Pattern visit(ru.itmo.stella.lang.Absyn.PatternList p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListPattern listpattern_ = new ru.itmo.stella.lang.Absyn.ListPattern();
      for (ru.itmo.stella.lang.Absyn.Pattern x : p.listpattern_)
      {
        listpattern_.add(x.accept(this,arg));
      }
      return new ru.itmo.stella.lang.Absyn.PatternList(listpattern_);
    }
    public ru.itmo.stella.lang.Absyn.Pattern visit(ru.itmo.stella.lang.Absyn.PatternCons p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Pattern pattern_1 = p.pattern_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Pattern pattern_2 = p.pattern_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.PatternCons(pattern_1, pattern_2);
    }
    public ru.itmo.stella.lang.Absyn.Pattern visit(ru.itmo.stella.lang.Absyn.PatternFalse p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.PatternFalse();
    }
    public ru.itmo.stella.lang.Absyn.Pattern visit(ru.itmo.stella.lang.Absyn.PatternTrue p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.PatternTrue();
    }
    public ru.itmo.stella.lang.Absyn.Pattern visit(ru.itmo.stella.lang.Absyn.PatternUnit p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.PatternUnit();
    }
    public ru.itmo.stella.lang.Absyn.Pattern visit(ru.itmo.stella.lang.Absyn.PatternInt p, A arg)
    {
      Integer integer_ = p.integer_;
      return new ru.itmo.stella.lang.Absyn.PatternInt(integer_);
    }
    public ru.itmo.stella.lang.Absyn.Pattern visit(ru.itmo.stella.lang.Absyn.PatternSucc p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Pattern pattern_ = p.pattern_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.PatternSucc(pattern_);
    }
    public ru.itmo.stella.lang.Absyn.Pattern visit(ru.itmo.stella.lang.Absyn.PatternVar p, A arg)
    {
      String stellaident_ = p.stellaident_;
      return new ru.itmo.stella.lang.Absyn.PatternVar(stellaident_);
    }

    /* LabelledPattern */
    public ru.itmo.stella.lang.Absyn.LabelledPattern visit(ru.itmo.stella.lang.Absyn.ALabelledPattern p, A arg)
    {
      String stellaident_ = p.stellaident_;
      ru.itmo.stella.lang.Absyn.Pattern pattern_ = p.pattern_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.ALabelledPattern(stellaident_, pattern_);
    }

    /* Binding */
    public ru.itmo.stella.lang.Absyn.Binding visit(ru.itmo.stella.lang.Absyn.ABinding p, A arg)
    {
      String stellaident_ = p.stellaident_;
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.ABinding(stellaident_, expr_);
    }

    /* Expr */
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Sequence p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Sequence(expr_1, expr_2);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Let p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListPatternBinding listpatternbinding_ = new ru.itmo.stella.lang.Absyn.ListPatternBinding();
      for (ru.itmo.stella.lang.Absyn.PatternBinding x : p.listpatternbinding_)
      {
        listpatternbinding_.add(x.accept(this,arg));
      }
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Let(listpatternbinding_, expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.LetRec p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListPatternBinding listpatternbinding_ = new ru.itmo.stella.lang.Absyn.ListPatternBinding();
      for (ru.itmo.stella.lang.Absyn.PatternBinding x : p.listpatternbinding_)
      {
        listpatternbinding_.add(x.accept(this,arg));
      }
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.LetRec(listpatternbinding_, expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.TypeAbstraction p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListStellaIdent liststellaident_ = p.liststellaident_;
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.TypeAbstraction(liststellaident_, expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Assign p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Assign(expr_1, expr_2);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.If p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_3 = p.expr_3.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.If(expr_1, expr_2, expr_3);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.LessThan p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.LessThan(expr_1, expr_2);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.LessThanOrEqual p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.LessThanOrEqual(expr_1, expr_2);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.GreaterThan p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.GreaterThan(expr_1, expr_2);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.GreaterThanOrEqual p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.GreaterThanOrEqual(expr_1, expr_2);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Equal p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Equal(expr_1, expr_2);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.NotEqual p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.NotEqual(expr_1, expr_2);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.TypeAsc p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.TypeAsc(expr_, type_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.TypeCast p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.TypeCast(expr_, type_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Abstraction p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListParamDecl listparamdecl_ = new ru.itmo.stella.lang.Absyn.ListParamDecl();
      for (ru.itmo.stella.lang.Absyn.ParamDecl x : p.listparamdecl_)
      {
        listparamdecl_.add(x.accept(this,arg));
      }
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Abstraction(listparamdecl_, expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Variant p, A arg)
    {
      String stellaident_ = p.stellaident_;
      ru.itmo.stella.lang.Absyn.ExprData exprdata_ = p.exprdata_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Variant(stellaident_, exprdata_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Match p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.ListMatchCase listmatchcase_ = new ru.itmo.stella.lang.Absyn.ListMatchCase();
      for (ru.itmo.stella.lang.Absyn.MatchCase x : p.listmatchcase_)
      {
        listmatchcase_.add(x.accept(this,arg));
      }
      return new ru.itmo.stella.lang.Absyn.Match(expr_, listmatchcase_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.List p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListExpr listexpr_ = new ru.itmo.stella.lang.Absyn.ListExpr();
      for (ru.itmo.stella.lang.Absyn.Expr x : p.listexpr_)
      {
        listexpr_.add(x.accept(this,arg));
      }
      return new ru.itmo.stella.lang.Absyn.List(listexpr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Add p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Add(expr_1, expr_2);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Subtract p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Subtract(expr_1, expr_2);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.LogicOr p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.LogicOr(expr_1, expr_2);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Multiply p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Multiply(expr_1, expr_2);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Divide p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Divide(expr_1, expr_2);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.LogicAnd p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.LogicAnd(expr_1, expr_2);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Ref p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Ref(expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Deref p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Deref(expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Application p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.ListExpr listexpr_ = new ru.itmo.stella.lang.Absyn.ListExpr();
      for (ru.itmo.stella.lang.Absyn.Expr x : p.listexpr_)
      {
        listexpr_.add(x.accept(this,arg));
      }
      return new ru.itmo.stella.lang.Absyn.Application(expr_, listexpr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.TypeApplication p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.ListType listtype_ = new ru.itmo.stella.lang.Absyn.ListType();
      for (ru.itmo.stella.lang.Absyn.Type x : p.listtype_)
      {
        listtype_.add(x.accept(this,arg));
      }
      return new ru.itmo.stella.lang.Absyn.TypeApplication(expr_, listtype_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.DotRecord p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      String stellaident_ = p.stellaident_;
      return new ru.itmo.stella.lang.Absyn.DotRecord(expr_, stellaident_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.DotTuple p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      Integer integer_ = p.integer_;
      return new ru.itmo.stella.lang.Absyn.DotTuple(expr_, integer_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Tuple p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListExpr listexpr_ = new ru.itmo.stella.lang.Absyn.ListExpr();
      for (ru.itmo.stella.lang.Absyn.Expr x : p.listexpr_)
      {
        listexpr_.add(x.accept(this,arg));
      }
      return new ru.itmo.stella.lang.Absyn.Tuple(listexpr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Record p, A arg)
    {
      ru.itmo.stella.lang.Absyn.ListBinding listbinding_ = new ru.itmo.stella.lang.Absyn.ListBinding();
      for (ru.itmo.stella.lang.Absyn.Binding x : p.listbinding_)
      {
        listbinding_.add(x.accept(this,arg));
      }
      return new ru.itmo.stella.lang.Absyn.Record(listbinding_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.ConsList p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.ConsList(expr_1, expr_2);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Head p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Head(expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.IsEmpty p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.IsEmpty(expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Tail p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Tail(expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Panic p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.Panic();
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Throw p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Throw(expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.TryCatch p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Pattern pattern_ = p.pattern_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.TryCatch(expr_1, pattern_, expr_2);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.TryWith p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.TryWith(expr_1, expr_2);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.TryCastAs p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Pattern pattern_ = p.pattern_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_3 = p.expr_3.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.TryCastAs(expr_1, type_, pattern_, expr_2, expr_3);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Inl p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Inl(expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Inr p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Inr(expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Succ p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Succ(expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.LogicNot p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.LogicNot(expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Pred p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Pred(expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.IsZero p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.IsZero(expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Fix p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Fix(expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.NatRec p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_3 = p.expr_3.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.NatRec(expr_1, expr_2, expr_3);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Fold p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Fold(type_, expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Unfold p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.Unfold(type_, expr_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.ConstTrue p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.ConstTrue();
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.ConstFalse p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.ConstFalse();
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.ConstUnit p, A arg)
    {
      return new ru.itmo.stella.lang.Absyn.ConstUnit();
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.ConstInt p, A arg)
    {
      Integer integer_ = p.integer_;
      return new ru.itmo.stella.lang.Absyn.ConstInt(integer_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.ConstMemory p, A arg)
    {
      String memoryaddress_ = p.memoryaddress_;
      return new ru.itmo.stella.lang.Absyn.ConstMemory(memoryaddress_);
    }
    public ru.itmo.stella.lang.Absyn.Expr visit(ru.itmo.stella.lang.Absyn.Var p, A arg)
    {
      String stellaident_ = p.stellaident_;
      return new ru.itmo.stella.lang.Absyn.Var(stellaident_);
    }

    /* PatternBinding */
    public ru.itmo.stella.lang.Absyn.PatternBinding visit(ru.itmo.stella.lang.Absyn.APatternBinding p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Pattern pattern_ = p.pattern_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.APatternBinding(pattern_, expr_);
    }

    /* VariantFieldType */
    public ru.itmo.stella.lang.Absyn.VariantFieldType visit(ru.itmo.stella.lang.Absyn.AVariantFieldType p, A arg)
    {
      String stellaident_ = p.stellaident_;
      ru.itmo.stella.lang.Absyn.OptionalTyping optionaltyping_ = p.optionaltyping_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.AVariantFieldType(stellaident_, optionaltyping_);
    }

    /* RecordFieldType */
    public ru.itmo.stella.lang.Absyn.RecordFieldType visit(ru.itmo.stella.lang.Absyn.ARecordFieldType p, A arg)
    {
      String stellaident_ = p.stellaident_;
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.ARecordFieldType(stellaident_, type_);
    }

    /* Typing */
    public ru.itmo.stella.lang.Absyn.Typing visit(ru.itmo.stella.lang.Absyn.ATyping p, A arg)
    {
      ru.itmo.stella.lang.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      ru.itmo.stella.lang.Absyn.Type type_ = p.type_.accept(this, arg);
      return new ru.itmo.stella.lang.Absyn.ATyping(expr_, type_);
    }
}
